### ISSUE TITLE
Labels present that disagree with the schema.

### ISSUE THREAD

**Issue by bryan-lunt** [sigmorphon2020/task0-data#3]
Previous Sigmorphon data has labeled the past-participle as "V;V.PTCP;PST" while this data contains some words labeled "V.PTCP.PST".

"V.PTCP.PST" does not appear in the Unimorph schema. ( https://unimorph.github.io/doc/unimorph-schema.pdf )

Will the schema be updated? Will the data be update? Should we be prepared to deal with labels that don't appear in the formal schema?

Thanks.

**Comment by ivri** [comment]
This year we preprocessed (canonicalized) the tags to make sure they 1) follow the same order; 2) a single feature is only assigned a single value. This is done with https://github.com/unimorph/um-canonicalize that uses tags.yaml file provided here (that lists all possible tags).

In this format,  "V;V.PTCP;PST" will be replaced with "V.PTCP;PST".  We canonicalized the majority of languages, and "myv", "mdf", "mhr", "krl" (where the issue occurs) are the only ones still being finalized and will be updated today.

**Comment by bryan-lunt** [comment]
ok, but what will be done about "V.PTCP.PST"?

**Comment by bryan-lunt** [comment]
I see. I await the update.

**Comment by ivri** [comment]
The tags should be fixed now.
