### ISSUE TITLE
Malformed YAML in tags.

### ISSUE THREAD

**Issue by bryan-lunt** [sigmorphon2020/task0-data#4]
Please quote at least the "ON" tag in the Case group.
(And I reccomend all tags, so that they are explicitly strings)

Yaml interprets 
```
- ON
```
as a boolean True value.

https://yaml.org/type/bool.html

**Comment by bryan-lunt** [comment]
https://github.com/sigmorphon2020/task0-data/blob/master/tags.yaml#L126

**Comment by ivri** [comment]
Good point. Fixed.
