### ISSUE TITLE
Specify test dataset file extension in advance.

### ISSUE THREAD

**Issue by bryan-lunt** [sigmorphon2020/task0-data#6]
It's not a huge deal, but it would be nice if we could know now what the file extensions for the test data are going to look like.

**Comment by ivri** [comment]
Do you mean the yaml file? It should contain the majority of tags and follow the UniMorph schema (https://unimorph.github.io/doc/unimorph-schema.pdf). There might be minor amendments (extra tags) that we will push shortly.

**Comment by bryan-lunt** [comment]
Thanks for that, I'll be sure to get it as soon as it becomes available.

That's not what I meant though. There are currently files with names such as "eng.trn" and "eng.dev" which I take to be training and validation sets. At the end, you're going to release final test data, right? (Or I am just assuming...)

What will the final test data for for example English be named? (Or will there _only_ be test data for the surprise languages?) "eng.test"? "eng.tst"?

**Comment by ivri** [comment]
Yes, we will release test files April, 20th:
Stage 3: Evaluation Phase
    April 20th, 2020: Test splits for all languages (both development and surprise) released.
    April 27th, 2020: Participants submit test predictions on all languages.

The file extension will be just .tst, i.e. eng.tst for English 

> Or will there only be test data for the surprise languages?

No, we will evaluate all languages
"In the Evaluation Phase, the participants’ models will be evaluated on held-out forms from all of the languages from the previous phases. The languages from the Development Phase and the Generalization Phase are evaluated simultaneously."

**Comment by bryan-lunt** [comment]
Great. Thanks.

**Comment by bryan-lunt** [comment]
Would it be considered cheating to include alphabet beyond what is just in the training data you gave us? (There would obviously be no way to train those characters, and any good regularization would bring the weights down to zero.)

If we saw for example, most but not all the characters of Cyrillic, I want to just use an alphabet with symbols for the entire Cyrillic alphabet (and some others for languages I hope, but of course have no idea, will be in the surprise set), but one of the people I'm working with insists it would be cheating and we can't do that. So uncommon letters are just not in the model.

**Comment by ivri** [comment]
there shouldn't be any extra characters in the test (beyond those you've seen in the training data). For convenience, I have added a file (alpha.all) listing all possible characters (in all three subsets).
